@BaseUrl=http://localhost:5000/api/v1

GET {{BaseUrl}}/tasks

###

GET {{BaseUrl}}/tasks/64aa3a8b44971e4318c6dbdc

###

PATCH {{BaseUrl}}/tasks/64aa3a8b44971e4318c6dbdc
Content-Type: application/json

{
    "name": "",
    "completed": false
}

###

DELETE {{BaseUrl}}/tasks/64aa3a8b44971e4318c6dbdc

###

POST {{BaseUrl}}/tasks
Content-Type: application/json

{
    "name": "Test 3",
    "completed": false
}